# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('factory', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requestDesigner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Designer'),
            preserve_default=False,
        ),
    ]
