# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factory', '0003_order_requestdesigner'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='targetManufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.Factory'),
            preserve_default=False,
        ),
    ]
