# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='fabric',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='material.Material'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='material.Material'),
        ),
    ]
